### ISSUE TITLE
[Submission]: Ferret Image from US gov archives

### ISSUE THREAD

**Issue by CoasterFan5** [tristan-f-r/ferret_images#3]
### Ferret Image

https://catalog.archives.gov/id/6521199

### What license do you want to use? (Commonly used is CC-BY-SA, but CC0 is the least restrictive)

Public Domain (CC0)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I agree to my chosen Creative Commons license above.

**Comment by LeoDog896** [comment]
Patched in [2c66bc8](https://github.com/LeoDog896/ferret_images/commit/2c66bc8031e0188fb474c8f2f934af690984643a).
